// Represents a user's "future self" path, including vision, timeframe, and weeks.
export interface Persona {
  id: string; // Unique ID (e.g., UUID from DB)
  title: string; // Derived from vision, e.g., "AI Builder Persona"
  vision: string; // User's raw input, e.g., "In 3 months, I want to be an AI builder..."
  timeframe: {
    duration: number; // In weeks (e.g., 12 for 3 months)
    startDate: Date; // When the persona was created/started
    estimatedEndDate: Date | null; // Calculated based on duration
  };
  status: "active" | "paused" | "archived" | "completed"; // For management
  alignmentScore: number; // Overall % (0-100), aggregated from weeks
  weeks: Week[]; // Array of weekly breakdowns (generated by AI)
  connections?: string[]; // Optional: IDs of linked personas (for interwoven paths)
  createdAt: Date;
  updatedAt: Date;
}

// Week Type
// Detailed narrative for each week in the persona's timeline.
// Based on our enhanced JSON structure for cards.
export interface Week {
  weekNumber: number; // e.g., 1
  title: string; // e.g., "Foundation Building"
  focus: string; // e.g., "Anchor in clarity: Start with 30-min journaling..."
  behaviors: string[]; // Array of key behaviors, e.g., ["Daily journaling", "Skill review"]
  todos: Todo[]; // Array of actionable items
  emotionalTone: string; // e.g., "Shift from overwhelm to curiosity"
  affirmations: string[]; // 1-3 motivational quotes/phrases
  challenges: {
    potentialHurdles: string; // e.g., "Work distractions"
    mitigations: string; // e.g., "Set a 5-min timer"
  };
  visualCues: {
    icon: string; // Emoji or icon name, e.g., "🌱"
    colorTheme: string; // e.g., "cool_blue_to_warm_green"
  };
  reflectivePrompt: string; // e.g., "How did these actions align?"
  shareableSnippet: string; // Pre-made social share text
  progress: {
    completedTodos: number; // e.g., 2/3
    alignment: number; // Week-specific % (0-100)
    reflection?: string | null; // User's input from reflection
  };
  status: "upcoming" | "in-progress" | "completed";
  updatedAt: Date; // Last adaptation time
}

// Todo Sub-Type
// Bite-sized actions within a week.
export interface Todo {
  day: string; // e.g., "Anytime (Daily)" or "Mon/Wed/Fri"
  task: string; // e.g., "Journal for 30 mins..."
  identityLink: string; // e.g., "This builds curiosity for your builder self"
  completed: boolean; // User-marked
}
